baseURL: "https://www.oso.nz"
languageCode: en-us
title: Curtis Fairweather - OSO NZ
theme: PaperMod

params:

  homeInfoParams:
      Title: G'day! I'm Curtis, welcome to my website. I know it's not pretty, but pretty doesn't get results.
      Content: I’m a Christchurch based SaaS CMO, Marketing Freelancer and about to be a PhD candidate at UC. Want me to fill your sales pipeline? Get in touch. Otherwise feel free to stick around, check out the projects I’m working on and read the learns I’ve documented in my wiki. 
      
  socialIcons:
  Name: facebook
  Url: “https://facebook.com/itscurtisf”
  Name: instagram
  Url: “https://linkedin.com/
  Name: linkedin
  Url: “https://instagram.com/ckfairweather

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true


menu: 
  main: 
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 10

    - identifier: wiki
      name: Wiki
      url: /wiki/
      weight: 20

    - identifier: contact
      name: Get in touch!
      url: /contact/
      weight: 30


markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      linkify: false