[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."sales-alert"]
  schedule = "0 * * * *"

[functions."deploy-alert"]
  schedule = "*/15 * * * *"
